//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/MultiplayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace MultiplayerInput
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/MultiplayerInput.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @MultiplayerInput: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @MultiplayerInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MultiplayerInput"",
    ""maps"": [
        {
            ""name"": ""Kiss"",
            ""id"": ""8156a137-6a4c-4d86-a43b-57e68486f809"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a90a83cf-8ac5-4909-97fd-f869a2524dd8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""345d9bcb-a5cf-41e2-a6ab-c54e8276c247"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Guitar"",
            ""id"": ""8945e514-f913-448e-9da1-5cb8ccfc6036"",
            ""actions"": [
                {
                    ""name"": ""ChangeChord"",
                    ""type"": ""Value"",
                    ""id"": ""a7ef87cb-574d-421d-a08e-c978bdb7563f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayChord"",
                    ""type"": ""Value"",
                    ""id"": ""6b7bb873-d2db-475b-8437-9db1e820e039"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b71877d8-45d7-4631-96e4-78914357437d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ChangeChord"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da40a847-a4ff-44ec-b525-a1e7c9d182a5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""PlayChord"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Drum"",
            ""id"": ""251f8a72-5955-48b3-912a-59d1689e06bb"",
            ""actions"": [
                {
                    ""name"": ""Cymbal"",
                    ""type"": ""Button"",
                    ""id"": ""8853aaec-9f53-402b-b9fd-f25f8b907392"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hat"",
                    ""type"": ""Button"",
                    ""id"": ""8de627e1-54d5-42e9-8d84-825b49c2fdb2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""eab9d3b3-3791-4df8-8b20-708b8248b2f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Snare"",
                    ""type"": ""Button"",
                    ""id"": ""9651edce-433a-47f4-a03f-6a83e6ca6809"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""61500f34-fa56-4e43-b008-86483ad59ff2"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cymbal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ce8929a-83f7-43f8-bb16-7f8747c0e7e8"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ad13320-996e-4bce-a2b9-b8842a3ec770"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01fe25a5-ddb5-44b9-85c7-9e24785c0b64"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Snare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Kiss
            m_Kiss = asset.FindActionMap("Kiss", throwIfNotFound: true);
            m_Kiss_Move = m_Kiss.FindAction("Move", throwIfNotFound: true);
            // Guitar
            m_Guitar = asset.FindActionMap("Guitar", throwIfNotFound: true);
            m_Guitar_ChangeChord = m_Guitar.FindAction("ChangeChord", throwIfNotFound: true);
            m_Guitar_PlayChord = m_Guitar.FindAction("PlayChord", throwIfNotFound: true);
            // Drum
            m_Drum = asset.FindActionMap("Drum", throwIfNotFound: true);
            m_Drum_Cymbal = m_Drum.FindAction("Cymbal", throwIfNotFound: true);
            m_Drum_Hat = m_Drum.FindAction("Hat", throwIfNotFound: true);
            m_Drum_Kick = m_Drum.FindAction("Kick", throwIfNotFound: true);
            m_Drum_Snare = m_Drum.FindAction("Snare", throwIfNotFound: true);
        }

        ~@MultiplayerInput()
        {
            UnityEngine.Debug.Assert(!m_Kiss.enabled, "This will cause a leak and performance issues, MultiplayerInput.Kiss.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Guitar.enabled, "This will cause a leak and performance issues, MultiplayerInput.Guitar.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Drum.enabled, "This will cause a leak and performance issues, MultiplayerInput.Drum.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Kiss
        private readonly InputActionMap m_Kiss;
        private List<IKissActions> m_KissActionsCallbackInterfaces = new List<IKissActions>();
        private readonly InputAction m_Kiss_Move;
        /// <summary>
        /// Provides access to input actions defined in input action map "Kiss".
        /// </summary>
        public struct KissActions
        {
            private @MultiplayerInput m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public KissActions(@MultiplayerInput wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Kiss/Move".
            /// </summary>
            public InputAction @Move => m_Wrapper.m_Kiss_Move;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Kiss; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="KissActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(KissActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="KissActions" />
            public void AddCallbacks(IKissActions instance)
            {
                if (instance == null || m_Wrapper.m_KissActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_KissActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="KissActions" />
            private void UnregisterCallbacks(IKissActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="KissActions.UnregisterCallbacks(IKissActions)" />.
            /// </summary>
            /// <seealso cref="KissActions.UnregisterCallbacks(IKissActions)" />
            public void RemoveCallbacks(IKissActions instance)
            {
                if (m_Wrapper.m_KissActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="KissActions.AddCallbacks(IKissActions)" />
            /// <seealso cref="KissActions.RemoveCallbacks(IKissActions)" />
            /// <seealso cref="KissActions.UnregisterCallbacks(IKissActions)" />
            public void SetCallbacks(IKissActions instance)
            {
                foreach (var item in m_Wrapper.m_KissActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_KissActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="KissActions" /> instance referencing this action map.
        /// </summary>
        public KissActions @Kiss => new KissActions(this);

        // Guitar
        private readonly InputActionMap m_Guitar;
        private List<IGuitarActions> m_GuitarActionsCallbackInterfaces = new List<IGuitarActions>();
        private readonly InputAction m_Guitar_ChangeChord;
        private readonly InputAction m_Guitar_PlayChord;
        /// <summary>
        /// Provides access to input actions defined in input action map "Guitar".
        /// </summary>
        public struct GuitarActions
        {
            private @MultiplayerInput m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public GuitarActions(@MultiplayerInput wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Guitar/ChangeChord".
            /// </summary>
            public InputAction @ChangeChord => m_Wrapper.m_Guitar_ChangeChord;
            /// <summary>
            /// Provides access to the underlying input action "Guitar/PlayChord".
            /// </summary>
            public InputAction @PlayChord => m_Wrapper.m_Guitar_PlayChord;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Guitar; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="GuitarActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(GuitarActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="GuitarActions" />
            public void AddCallbacks(IGuitarActions instance)
            {
                if (instance == null || m_Wrapper.m_GuitarActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GuitarActionsCallbackInterfaces.Add(instance);
                @ChangeChord.started += instance.OnChangeChord;
                @ChangeChord.performed += instance.OnChangeChord;
                @ChangeChord.canceled += instance.OnChangeChord;
                @PlayChord.started += instance.OnPlayChord;
                @PlayChord.performed += instance.OnPlayChord;
                @PlayChord.canceled += instance.OnPlayChord;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="GuitarActions" />
            private void UnregisterCallbacks(IGuitarActions instance)
            {
                @ChangeChord.started -= instance.OnChangeChord;
                @ChangeChord.performed -= instance.OnChangeChord;
                @ChangeChord.canceled -= instance.OnChangeChord;
                @PlayChord.started -= instance.OnPlayChord;
                @PlayChord.performed -= instance.OnPlayChord;
                @PlayChord.canceled -= instance.OnPlayChord;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GuitarActions.UnregisterCallbacks(IGuitarActions)" />.
            /// </summary>
            /// <seealso cref="GuitarActions.UnregisterCallbacks(IGuitarActions)" />
            public void RemoveCallbacks(IGuitarActions instance)
            {
                if (m_Wrapper.m_GuitarActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="GuitarActions.AddCallbacks(IGuitarActions)" />
            /// <seealso cref="GuitarActions.RemoveCallbacks(IGuitarActions)" />
            /// <seealso cref="GuitarActions.UnregisterCallbacks(IGuitarActions)" />
            public void SetCallbacks(IGuitarActions instance)
            {
                foreach (var item in m_Wrapper.m_GuitarActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GuitarActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="GuitarActions" /> instance referencing this action map.
        /// </summary>
        public GuitarActions @Guitar => new GuitarActions(this);

        // Drum
        private readonly InputActionMap m_Drum;
        private List<IDrumActions> m_DrumActionsCallbackInterfaces = new List<IDrumActions>();
        private readonly InputAction m_Drum_Cymbal;
        private readonly InputAction m_Drum_Hat;
        private readonly InputAction m_Drum_Kick;
        private readonly InputAction m_Drum_Snare;
        /// <summary>
        /// Provides access to input actions defined in input action map "Drum".
        /// </summary>
        public struct DrumActions
        {
            private @MultiplayerInput m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public DrumActions(@MultiplayerInput wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Drum/Cymbal".
            /// </summary>
            public InputAction @Cymbal => m_Wrapper.m_Drum_Cymbal;
            /// <summary>
            /// Provides access to the underlying input action "Drum/Hat".
            /// </summary>
            public InputAction @Hat => m_Wrapper.m_Drum_Hat;
            /// <summary>
            /// Provides access to the underlying input action "Drum/Kick".
            /// </summary>
            public InputAction @Kick => m_Wrapper.m_Drum_Kick;
            /// <summary>
            /// Provides access to the underlying input action "Drum/Snare".
            /// </summary>
            public InputAction @Snare => m_Wrapper.m_Drum_Snare;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Drum; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="DrumActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(DrumActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="DrumActions" />
            public void AddCallbacks(IDrumActions instance)
            {
                if (instance == null || m_Wrapper.m_DrumActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DrumActionsCallbackInterfaces.Add(instance);
                @Cymbal.started += instance.OnCymbal;
                @Cymbal.performed += instance.OnCymbal;
                @Cymbal.canceled += instance.OnCymbal;
                @Hat.started += instance.OnHat;
                @Hat.performed += instance.OnHat;
                @Hat.canceled += instance.OnHat;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Snare.started += instance.OnSnare;
                @Snare.performed += instance.OnSnare;
                @Snare.canceled += instance.OnSnare;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="DrumActions" />
            private void UnregisterCallbacks(IDrumActions instance)
            {
                @Cymbal.started -= instance.OnCymbal;
                @Cymbal.performed -= instance.OnCymbal;
                @Cymbal.canceled -= instance.OnCymbal;
                @Hat.started -= instance.OnHat;
                @Hat.performed -= instance.OnHat;
                @Hat.canceled -= instance.OnHat;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Snare.started -= instance.OnSnare;
                @Snare.performed -= instance.OnSnare;
                @Snare.canceled -= instance.OnSnare;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DrumActions.UnregisterCallbacks(IDrumActions)" />.
            /// </summary>
            /// <seealso cref="DrumActions.UnregisterCallbacks(IDrumActions)" />
            public void RemoveCallbacks(IDrumActions instance)
            {
                if (m_Wrapper.m_DrumActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="DrumActions.AddCallbacks(IDrumActions)" />
            /// <seealso cref="DrumActions.RemoveCallbacks(IDrumActions)" />
            /// <seealso cref="DrumActions.UnregisterCallbacks(IDrumActions)" />
            public void SetCallbacks(IDrumActions instance)
            {
                foreach (var item in m_Wrapper.m_DrumActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DrumActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="DrumActions" /> instance referencing this action map.
        /// </summary>
        public DrumActions @Drum => new DrumActions(this);
        private int m_GamepadSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Kiss" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="KissActions.AddCallbacks(IKissActions)" />
        /// <seealso cref="KissActions.RemoveCallbacks(IKissActions)" />
        public interface IKissActions
        {
            /// <summary>
            /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMove(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Guitar" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="GuitarActions.AddCallbacks(IGuitarActions)" />
        /// <seealso cref="GuitarActions.RemoveCallbacks(IGuitarActions)" />
        public interface IGuitarActions
        {
            /// <summary>
            /// Method invoked when associated input action "ChangeChord" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnChangeChord(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "PlayChord" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPlayChord(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Drum" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="DrumActions.AddCallbacks(IDrumActions)" />
        /// <seealso cref="DrumActions.RemoveCallbacks(IDrumActions)" />
        public interface IDrumActions
        {
            /// <summary>
            /// Method invoked when associated input action "Cymbal" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCymbal(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Hat" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnHat(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Kick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnKick(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Snare" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSnare(InputAction.CallbackContext context);
        }
    }
}
